// platform_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 19.1 670

`timescale 1 ps / 1 ps
module platform_mm_interconnect_1 (
		input  wire        sys_sdram_pll_sys_clk_clk,                                  //                                sys_sdram_pll_sys_clk.clk
		input  wire        Instruction_Cache_0_reset_sink_reset_bridge_in_reset_reset, // Instruction_Cache_0_reset_sink_reset_bridge_in_reset.reset
		input  wire        riscv_simple_sv_0_reset_reset_bridge_in_reset_reset,        //        riscv_simple_sv_0_reset_reset_bridge_in_reset.reset
		input  wire [31:0] riscv_simple_sv_0_text_master_address,                      //                        riscv_simple_sv_0_text_master.address
		output wire        riscv_simple_sv_0_text_master_waitrequest,                  //                                                     .waitrequest
		input  wire        riscv_simple_sv_0_text_master_read,                         //                                                     .read
		output wire [31:0] riscv_simple_sv_0_text_master_readdata,                     //                                                     .readdata
		output wire        riscv_simple_sv_0_text_master_readdatavalid,                //                                                     .readdatavalid
		output wire [31:0] Instruction_Cache_0_core_interaface_address,                //                  Instruction_Cache_0_core_interaface.address
		output wire        Instruction_Cache_0_core_interaface_read,                   //                                                     .read
		input  wire [31:0] Instruction_Cache_0_core_interaface_readdata,               //                                                     .readdata
		input  wire        Instruction_Cache_0_core_interaface_readdatavalid,          //                                                     .readdatavalid
		input  wire        Instruction_Cache_0_core_interaface_waitrequest             //                                                     .waitrequest
	);

	wire         riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_waitrequest;   // Instruction_Cache_0_core_interaface_translator:uav_waitrequest -> riscv_simple_sv_0_text_master_translator:uav_waitrequest
	wire  [31:0] riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_readdata;      // Instruction_Cache_0_core_interaface_translator:uav_readdata -> riscv_simple_sv_0_text_master_translator:uav_readdata
	wire         riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_debugaccess;   // riscv_simple_sv_0_text_master_translator:uav_debugaccess -> Instruction_Cache_0_core_interaface_translator:uav_debugaccess
	wire  [31:0] riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_address;       // riscv_simple_sv_0_text_master_translator:uav_address -> Instruction_Cache_0_core_interaface_translator:uav_address
	wire         riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_read;          // riscv_simple_sv_0_text_master_translator:uav_read -> Instruction_Cache_0_core_interaface_translator:uav_read
	wire   [3:0] riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_byteenable;    // riscv_simple_sv_0_text_master_translator:uav_byteenable -> Instruction_Cache_0_core_interaface_translator:uav_byteenable
	wire         riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_readdatavalid; // Instruction_Cache_0_core_interaface_translator:uav_readdatavalid -> riscv_simple_sv_0_text_master_translator:uav_readdatavalid
	wire         riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_lock;          // riscv_simple_sv_0_text_master_translator:uav_lock -> Instruction_Cache_0_core_interaface_translator:uav_lock
	wire         riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_write;         // riscv_simple_sv_0_text_master_translator:uav_write -> Instruction_Cache_0_core_interaface_translator:uav_write
	wire  [31:0] riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_writedata;     // riscv_simple_sv_0_text_master_translator:uav_writedata -> Instruction_Cache_0_core_interaface_translator:uav_writedata
	wire   [2:0] riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_burstcount;    // riscv_simple_sv_0_text_master_translator:uav_burstcount -> Instruction_Cache_0_core_interaface_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (1),
		.USE_WRITE                   (0),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (1),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) riscv_simple_sv_0_text_master_translator (
		.clk                    (sys_sdram_pll_sys_clk_clk),                                                        //                       clk.clk
		.reset                  (riscv_simple_sv_0_reset_reset_bridge_in_reset_reset),                              //                     reset.reset
		.uav_address            (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (riscv_simple_sv_0_text_master_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (riscv_simple_sv_0_text_master_waitrequest),                                        //                          .waitrequest
		.av_read                (riscv_simple_sv_0_text_master_read),                                               //                          .read
		.av_readdata            (riscv_simple_sv_0_text_master_readdata),                                           //                          .readdata
		.av_readdatavalid       (riscv_simple_sv_0_text_master_readdatavalid),                                      //                          .readdatavalid
		.av_burstcount          (1'b1),                                                                             //               (terminated)
		.av_byteenable          (4'b1111),                                                                          //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                                             //               (terminated)
		.av_write               (1'b0),                                                                             //               (terminated)
		.av_writedata           (32'b00000000000000000000000000000000),                                             //               (terminated)
		.av_lock                (1'b0),                                                                             //               (terminated)
		.av_debugaccess         (1'b0),                                                                             //               (terminated)
		.uav_clken              (),                                                                                 //               (terminated)
		.av_clken               (1'b1),                                                                             //               (terminated)
		.uav_response           (2'b00),                                                                            //               (terminated)
		.av_response            (),                                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (32),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (1),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) instruction_cache_0_core_interaface_translator (
		.clk                    (sys_sdram_pll_sys_clk_clk),                                                        //                      clk.clk
		.reset                  (Instruction_Cache_0_reset_sink_reset_bridge_in_reset_reset),                       //                    reset.reset
		.uav_address            (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (riscv_simple_sv_0_text_master_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (Instruction_Cache_0_core_interaface_address),                                      //      avalon_anti_slave_0.address
		.av_read                (Instruction_Cache_0_core_interaface_read),                                         //                         .read
		.av_readdata            (Instruction_Cache_0_core_interaface_readdata),                                     //                         .readdata
		.av_readdatavalid       (Instruction_Cache_0_core_interaface_readdatavalid),                                //                         .readdatavalid
		.av_waitrequest         (Instruction_Cache_0_core_interaface_waitrequest),                                  //                         .waitrequest
		.av_write               (),                                                                                 //              (terminated)
		.av_writedata           (),                                                                                 //              (terminated)
		.av_begintransfer       (),                                                                                 //              (terminated)
		.av_beginbursttransfer  (),                                                                                 //              (terminated)
		.av_burstcount          (),                                                                                 //              (terminated)
		.av_byteenable          (),                                                                                 //              (terminated)
		.av_writebyteenable     (),                                                                                 //              (terminated)
		.av_lock                (),                                                                                 //              (terminated)
		.av_chipselect          (),                                                                                 //              (terminated)
		.av_clken               (),                                                                                 //              (terminated)
		.uav_clken              (1'b0),                                                                             //              (terminated)
		.av_debugaccess         (),                                                                                 //              (terminated)
		.av_outputenable        (),                                                                                 //              (terminated)
		.uav_response           (),                                                                                 //              (terminated)
		.av_response            (2'b00),                                                                            //              (terminated)
		.uav_writeresponsevalid (),                                                                                 //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                              //              (terminated)
	);

endmodule
