dist: xenial
language: minimal

services:
    - docker

before_install:
    - docker pull tilk/riscv-gnu-toolchain
    - docker run --name rv -t -d tilk/riscv-gnu-toolchain /bin/bash
    - docker exec rv apt-get update
    - docker exec rv apt-get install -y verilator g++
    - docker cp . rv:/root/rv

script:
    - docker exec --env PATH=/root/riscv-prefix/bin:/usr/bin:/bin rv bash -c "cd rv/tests && make"
    - docker exec rv bash -c "cd rv/testbench; make"
#    - rm -rf tests
#    - docker cp rv:/root/tests tests
#    - verilator --version
#    - cd testbench; make

