# TCL File Generated by Component Editor 19.1
# Mon Jan 27 14:53:45 CET 2020
# DO NOT MODIFY


# 
# Mem_convertor "Mem_convertor" v1.0
# Maciej Dudek 2020.01.27.14:53:45
# Converst burst to single accesses
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module Mem_convertor
# 
set_module_property DESCRIPTION "Converst burst to single accesses"
set_module_property NAME Mem_convertor
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Ospis
set_module_property AUTHOR "Maciej Dudek"
set_module_property DISPLAY_NAME Mem_convertor
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mem_convertor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mem_convertor.v VERILOG PATH mem_convertor.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point cache_interface
# 
add_interface cache_interface avalon end
set_interface_property cache_interface addressUnits SYMBOLS
set_interface_property cache_interface associatedClock clock
set_interface_property cache_interface associatedReset reset
set_interface_property cache_interface bitsPerSymbol 8
set_interface_property cache_interface burstOnBurstBoundariesOnly false
set_interface_property cache_interface burstcountUnits SYMBOLS
set_interface_property cache_interface explicitAddressSpan 0
set_interface_property cache_interface holdTime 0
set_interface_property cache_interface linewrapBursts false
set_interface_property cache_interface maximumPendingReadTransactions 1
set_interface_property cache_interface maximumPendingWriteTransactions 0
set_interface_property cache_interface readLatency 0
set_interface_property cache_interface readWaitTime 1
set_interface_property cache_interface setupTime 0
set_interface_property cache_interface timingUnits Cycles
set_interface_property cache_interface writeWaitTime 0
set_interface_property cache_interface ENABLED true
set_interface_property cache_interface EXPORT_OF ""
set_interface_property cache_interface PORT_NAME_MAP ""
set_interface_property cache_interface CMSIS_SVD_VARIABLES ""
set_interface_property cache_interface SVD_ADDRESS_GROUP ""

add_interface_port cache_interface cache_address address Input 32
add_interface_port cache_interface cache_burstcount burstcount Input 4
add_interface_port cache_interface cache_readdatavalid readdatavalid Output 1
add_interface_port cache_interface cache_readdata readdata Output 64
add_interface_port cache_interface cache_read read Input 1
add_interface_port cache_interface cache_waitrequest waitrequest Output 1
set_interface_assignment cache_interface embeddedsw.configuration.isFlash 0
set_interface_assignment cache_interface embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment cache_interface embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment cache_interface embeddedsw.configuration.isPrintableDevice 0


# 
# connection point memory_interface
# 
add_interface memory_interface avalon start
set_interface_property memory_interface addressUnits SYMBOLS
set_interface_property memory_interface associatedClock clock
set_interface_property memory_interface associatedReset reset
set_interface_property memory_interface bitsPerSymbol 8
set_interface_property memory_interface burstOnBurstBoundariesOnly false
set_interface_property memory_interface burstcountUnits WORDS
set_interface_property memory_interface doStreamReads false
set_interface_property memory_interface doStreamWrites false
set_interface_property memory_interface holdTime 0
set_interface_property memory_interface linewrapBursts false
set_interface_property memory_interface maximumPendingReadTransactions 0
set_interface_property memory_interface maximumPendingWriteTransactions 0
set_interface_property memory_interface readLatency 0
set_interface_property memory_interface readWaitTime 1
set_interface_property memory_interface setupTime 0
set_interface_property memory_interface timingUnits Cycles
set_interface_property memory_interface writeWaitTime 0
set_interface_property memory_interface ENABLED true
set_interface_property memory_interface EXPORT_OF ""
set_interface_property memory_interface PORT_NAME_MAP ""
set_interface_property memory_interface CMSIS_SVD_VARIABLES ""
set_interface_property memory_interface SVD_ADDRESS_GROUP ""

add_interface_port memory_interface memory_address address Output 32
add_interface_port memory_interface memory_readdata readdata Input 32
add_interface_port memory_interface memory_read read Output 1
add_interface_port memory_interface memory_readdatavalid readdatavalid Input 1
add_interface_port memory_interface memory_waitrequest waitrequest Input 1

