# TCL File Generated by Component Editor 19.1
# Mon Dec 02 13:56:27 CET 2019
# DO NOT MODIFY


# 
# riscv_simple_sv "riscv_simple_sv" v1.0
# Marek Materzok 2019.12.02.13:56:27
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module riscv_simple_sv
# 
set_module_property DESCRIPTION ""
set_module_property NAME riscv_simple_sv
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP tilk
set_module_property AUTHOR "Marek Materzok"
set_module_property DISPLAY_NAME riscv_simple_sv
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL riscv_core
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file riscv_core.sv SYSTEM_VERILOG PATH singlecycle/riscv_core.sv TOP_LEVEL_FILE
add_fileset_file adder.sv SYSTEM_VERILOG PATH singlecycle/adder.sv
add_fileset_file alu.sv SYSTEM_VERILOG PATH singlecycle/alu.sv
add_fileset_file alu_control.sv SYSTEM_VERILOG PATH singlecycle/alu_control.sv
add_fileset_file config.sv SYSTEM_VERILOG PATH singlecycle/config.sv
add_fileset_file constants.sv SYSTEM_VERILOG PATH singlecycle/constants.sv
add_fileset_file control_transfer.sv SYSTEM_VERILOG PATH singlecycle/control_transfer.sv
add_fileset_file data_memory_interface.sv SYSTEM_VERILOG PATH singlecycle/data_memory_interface.sv
add_fileset_file immediate_generator.sv SYSTEM_VERILOG PATH singlecycle/immediate_generator.sv
add_fileset_file instruction_decoder.sv SYSTEM_VERILOG PATH singlecycle/instruction_decoder.sv
add_fileset_file multiplexer.sv SYSTEM_VERILOG PATH singlecycle/multiplexer.sv
add_fileset_file multiplexer2.sv SYSTEM_VERILOG PATH singlecycle/multiplexer2.sv
add_fileset_file multiplexer4.sv SYSTEM_VERILOG PATH singlecycle/multiplexer4.sv
add_fileset_file multiplexer8.sv SYSTEM_VERILOG PATH singlecycle/multiplexer8.sv
add_fileset_file regfile.sv SYSTEM_VERILOG PATH singlecycle/regfile.sv
add_fileset_file register.sv SYSTEM_VERILOG PATH singlecycle/register.sv
add_fileset_file singlecycle_control.sv SYSTEM_VERILOG PATH singlecycle/singlecycle_control.sv
add_fileset_file singlecycle_ctlpath.sv SYSTEM_VERILOG PATH singlecycle/singlecycle_ctlpath.sv
add_fileset_file singlecycle_datapath.sv SYSTEM_VERILOG PATH singlecycle/singlecycle_datapath.sv
add_fileset_file text_memory_interface.sv SYSTEM_VERILOG PATH singlecycle/text_memory_interface.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point text_master
# 
add_interface text_master avalon start
set_interface_property text_master addressUnits SYMBOLS
set_interface_property text_master associatedClock clock
set_interface_property text_master associatedReset reset
set_interface_property text_master bitsPerSymbol 8
set_interface_property text_master burstOnBurstBoundariesOnly false
set_interface_property text_master burstcountUnits WORDS
set_interface_property text_master doStreamReads false
set_interface_property text_master doStreamWrites false
set_interface_property text_master holdTime 0
set_interface_property text_master linewrapBursts false
set_interface_property text_master maximumPendingReadTransactions 0
set_interface_property text_master maximumPendingWriteTransactions 0
set_interface_property text_master readLatency 0
set_interface_property text_master readWaitTime 1
set_interface_property text_master setupTime 0
set_interface_property text_master timingUnits Cycles
set_interface_property text_master writeWaitTime 0
set_interface_property text_master ENABLED true
set_interface_property text_master EXPORT_OF ""
set_interface_property text_master PORT_NAME_MAP ""
set_interface_property text_master CMSIS_SVD_VARIABLES ""
set_interface_property text_master SVD_ADDRESS_GROUP ""

add_interface_port text_master pc address Output 32
add_interface_port text_master inst_data readdata Input 32
add_interface_port text_master inst_valid readdatavalid Input 1
add_interface_port text_master inst_wait_req waitrequest Input 1
add_interface_port text_master inst_read_enable read Output 1


# 
# connection point data_master
# 
add_interface data_master avalon start
set_interface_property data_master addressUnits SYMBOLS
set_interface_property data_master associatedClock clock
set_interface_property data_master associatedReset reset
set_interface_property data_master bitsPerSymbol 8
set_interface_property data_master burstOnBurstBoundariesOnly false
set_interface_property data_master burstcountUnits WORDS
set_interface_property data_master doStreamReads false
set_interface_property data_master doStreamWrites false
set_interface_property data_master holdTime 0
set_interface_property data_master linewrapBursts false
set_interface_property data_master maximumPendingReadTransactions 0
set_interface_property data_master maximumPendingWriteTransactions 0
set_interface_property data_master readLatency 0
set_interface_property data_master readWaitTime 1
set_interface_property data_master setupTime 0
set_interface_property data_master timingUnits Cycles
set_interface_property data_master writeWaitTime 0
set_interface_property data_master ENABLED true
set_interface_property data_master EXPORT_OF ""
set_interface_property data_master PORT_NAME_MAP ""
set_interface_property data_master CMSIS_SVD_VARIABLES ""
set_interface_property data_master SVD_ADDRESS_GROUP ""

add_interface_port data_master bus_address address Output 32
add_interface_port data_master bus_read_data readdata Input 32
add_interface_port data_master bus_write_data writedata Output 32
add_interface_port data_master bus_byte_enable byteenable Output 4
add_interface_port data_master bus_read_enable read Output 1
add_interface_port data_master bus_write_enable write Output 1
add_interface_port data_master bus_wait_req waitrequest Input 1
add_interface_port data_master bus_valid readdatavalid Input 1

